// Code generated by mountproto/gen; DO NOT EDIT.

package mountproto

const Version uint16 = 1
const Build = "fusekit.mount.ae5ff28cfe8e714560fbc540499d0da3d8ac592498bf6874034df53c15fe43bf"

type Operation string

const (
	OperationTenantRegister Operation = "tenant.register"
	OperationTenantReplace  Operation = "tenant.replace"
	OperationTenantRemove   Operation = "tenant.remove"
	OperationTenantPrepare  Operation = "tenant.prepare"
	OperationTenantState    Operation = "tenant.state"
)

type ErrorCode string

const (
	ErrorCodeOk             ErrorCode = "ok"
	ErrorCodeInvalidRequest ErrorCode = "invalid_request"
	ErrorCodeUnauthorized   ErrorCode = "unauthorized"
	ErrorCodeNotFound       ErrorCode = "not_found"
	ErrorCodeConflict       ErrorCode = "conflict"
	ErrorCodeQuarantined    ErrorCode = "quarantined"
	ErrorCodeCanceled       ErrorCode = "canceled"
	ErrorCodeUnavailable    ErrorCode = "unavailable"
)

type AccessMode string

const (
	AccessModeReadOnly  AccessMode = "read_only"
	AccessModeReadWrite AccessMode = "read_write"
)

type CasePolicy string

const (
	CasePolicySensitive   CasePolicy = "sensitive"
	CasePolicyInsensitive CasePolicy = "insensitive"
)

type Presentation string

const (
	PresentationMount        Presentation = "mount"
	PresentationFileProvider Presentation = "file_provider"
)

type QuarantineLane string

const (
	QuarantineLaneCatalogMutation QuarantineLane = "catalog_mutation"
	QuarantineLaneMaterialization QuarantineLane = "materialization"
	QuarantineLaneEnumeration     QuarantineLane = "enumeration"
	QuarantineLaneMountLifecycle  QuarantineLane = "mount_lifecycle"
)

type QuarantineCause string

const (
	QuarantineCauseConflict    QuarantineCause = "conflict"
	QuarantineCauseIntegrity   QuarantineCause = "integrity"
	QuarantineCauseUnsettled   QuarantineCause = "unsettled"
	QuarantineCauseUnavailable QuarantineCause = "unavailable"
)

type TenantID string

type TenantDefinition struct {
	PresentationRoot string         `json:"presentation_root"`
	BackingRoot      string         `json:"backing_root"`
	ContentSourceID  string         `json:"content_source_id"`
	AccessMode       AccessMode     `json:"access_mode"`
	CasePolicy       CasePolicy     `json:"case_policy"`
	Presentations    []Presentation `json:"presentations"`
	Generation       uint64         `json:"generation"`
}

type Quarantine struct {
	Lane          QuarantineLane  `json:"lane"`
	Revision      uint64          `json:"revision"`
	Cause         QuarantineCause `json:"cause"`
	Detail        string          `json:"detail"`
	SinceUnixNano int64           `json:"since_unix_nano"`
}

type TenantState struct {
	TenantID            TenantID    `json:"tenant_id"`
	Generation          uint64      `json:"generation"`
	Requested           uint64      `json:"requested"`
	Desired             uint64      `json:"desired"`
	Observed            uint64      `json:"observed"`
	Verified            uint64      `json:"verified"`
	Applied             uint64      `json:"applied"`
	ActivatedGeneration uint64      `json:"activated_generation"`
	StateVersion        uint64      `json:"state_version"`
	Quarantine          *Quarantine `json:"quarantine,omitempty"`
}

type RegisterTenantRequest struct {
	Protocol   uint16           `json:"protocol"`
	Definition TenantDefinition `json:"definition"`
}

type RegisterTenantResponse struct {
	Protocol   uint16    `json:"protocol"`
	Code       ErrorCode `json:"code"`
	Message    string    `json:"message"`
	TenantID   TenantID  `json:"tenant_id"`
	Generation uint64    `json:"generation"`
}

type ReplaceTenantRequest struct {
	Protocol           uint16           `json:"protocol"`
	ExpectedGeneration uint64           `json:"expected_generation"`
	Definition         TenantDefinition `json:"definition"`
}

type ReplaceTenantResponse struct {
	Protocol   uint16    `json:"protocol"`
	Code       ErrorCode `json:"code"`
	Message    string    `json:"message"`
	TenantID   TenantID  `json:"tenant_id"`
	Generation uint64    `json:"generation"`
}

type RemoveTenantRequest struct {
	Protocol   uint16 `json:"protocol"`
	Generation uint64 `json:"generation"`
}

type RemoveTenantResponse struct {
	Protocol   uint16    `json:"protocol"`
	Code       ErrorCode `json:"code"`
	Message    string    `json:"message"`
	TenantID   TenantID  `json:"tenant_id"`
	Generation uint64    `json:"generation"`
}

type PrepareTenantRequest struct {
	Protocol   uint16 `json:"protocol"`
	Generation uint64 `json:"generation"`
	Revision   uint64 `json:"revision"`
}

type PrepareTenantResponse struct {
	Protocol uint16       `json:"protocol"`
	Code     ErrorCode    `json:"code"`
	Message  string       `json:"message"`
	State    *TenantState `json:"state,omitempty"`
}

type StateRequest struct {
	Protocol   uint16 `json:"protocol"`
	Generation uint64 `json:"generation"`
}

type StateResponse struct {
	Protocol uint16       `json:"protocol"`
	Code     ErrorCode    `json:"code"`
	Message  string       `json:"message"`
	State    *TenantState `json:"state,omitempty"`
}
