// Code generated by mountproto/gen; DO NOT EDIT.

package mountproto

const Version uint16 = 1
const SchemaFingerprint = "fusekit.mount.f19ee91dbe7d120354c015658934ea1be1faffb8017515de6fe9cf36d4884bb9"

type Operation string

const (
	OperationRuntimeHealth       Operation = "runtime.health"
	OperationTenantProvision     Operation = "tenant.provision"
	OperationTenantReplace       Operation = "tenant.replace"
	OperationTenantRemove        Operation = "tenant.remove"
	OperationTenantState         Operation = "tenant.state"
	OperationNativeBind          Operation = "native.bind"
	OperationNativeMounted       Operation = "native.mounted"
	OperationNativeReady         Operation = "native.ready"
	OperationNativeUnbind        Operation = "native.unbind"
	OperationNativeRoutePage     Operation = "native.route.page"
	OperationNativePin           Operation = "native.pin"
	OperationNativeRelease       Operation = "native.release"
	OperationNativeSnapshotOpen  Operation = "native.snapshot.open"
	OperationNativeSnapshotRead  Operation = "native.snapshot.read"
	OperationNativeSnapshotClose Operation = "native.snapshot.close"
	OperationNativeWriteOpen     Operation = "native.write.open"
	OperationNativeWriteRead     Operation = "native.write.read"
	OperationNativeWriteWrite    Operation = "native.write.write"
	OperationNativeWriteTruncate Operation = "native.write.truncate"
	OperationNativeWriteSync     Operation = "native.write.sync"
	OperationNativeWriteCommit   Operation = "native.write.commit"
	OperationNativeWriteAbort    Operation = "native.write.abort"
)

type ErrorCode string

const (
	ErrorCodeOk             ErrorCode = "ok"
	ErrorCodeInvalidRequest ErrorCode = "invalid_request"
	ErrorCodeUnauthorized   ErrorCode = "unauthorized"
	ErrorCodeNotFound       ErrorCode = "not_found"
	ErrorCodeConflict       ErrorCode = "conflict"
	ErrorCodeQuarantined    ErrorCode = "quarantined"
	ErrorCodeCanceled       ErrorCode = "canceled"
	ErrorCodeUnavailable    ErrorCode = "unavailable"
)

type AccessMode string

const (
	AccessModeReadOnly  AccessMode = "read_only"
	AccessModeReadWrite AccessMode = "read_write"
)

type CasePolicy string

const (
	CasePolicySensitive   CasePolicy = "sensitive"
	CasePolicyInsensitive CasePolicy = "insensitive"
)

type Presentation string

const (
	PresentationMount        Presentation = "mount"
	PresentationFileProvider Presentation = "file_provider"
)

type QuarantineLane string

const (
	QuarantineLaneCatalogMutation QuarantineLane = "catalog_mutation"
	QuarantineLaneMaterialization QuarantineLane = "materialization"
	QuarantineLaneEnumeration     QuarantineLane = "enumeration"
	QuarantineLaneMountLifecycle  QuarantineLane = "mount_lifecycle"
)

type QuarantineCause string

const (
	QuarantineCauseConflict    QuarantineCause = "conflict"
	QuarantineCauseIntegrity   QuarantineCause = "integrity"
	QuarantineCauseUnsettled   QuarantineCause = "unsettled"
	QuarantineCauseUnavailable QuarantineCause = "unavailable"
)

type ObjectKind string

const (
	ObjectKindDirectory ObjectKind = "directory"
	ObjectKindFile      ObjectKind = "file"
	ObjectKindSymlink   ObjectKind = "symlink"
)

type ReadinessPhase string

const (
	ReadinessPhaseStarting ReadinessPhase = "starting"
	ReadinessPhaseReady    ReadinessPhase = "ready"
	ReadinessPhaseFailed   ReadinessPhase = "failed"
)

type ReadinessStep string

const (
	ReadinessStepListener  ReadinessStep = "listener"
	ReadinessStepNative    ReadinessStep = "native"
	ReadinessStepBroker    ReadinessStep = "broker"
	ReadinessStepReceipts  ReadinessStep = "receipts"
	ReadinessStepPublished ReadinessStep = "published"
)

type NativePhase string

const (
	NativePhaseIdle     NativePhase = "idle"
	NativePhaseStarting NativePhase = "starting"
	NativePhaseLive     NativePhase = "live"
	NativePhaseFailed   NativePhase = "failed"
	NativePhaseClosing  NativePhase = "closing"
	NativePhaseClosed   NativePhase = "closed"
)

type BrokerPhase string

const (
	BrokerPhaseDisabled BrokerPhase = "disabled"
	BrokerPhaseStarting BrokerPhase = "starting"
	BrokerPhaseLive     BrokerPhase = "live"
	BrokerPhaseFailed   BrokerPhase = "failed"
)

type TenantID string
type OwnerID string
type MutationID string

type TenantDefinition struct {
	PresentationRoot        string         `json:"presentation_root"`
	BackingRoot             string         `json:"backing_root"`
	ContentSourceID         string         `json:"content_source_id"`
	AccessMode              AccessMode     `json:"access_mode"`
	CasePolicy              CasePolicy     `json:"case_policy"`
	Presentations           []Presentation `json:"presentations"`
	FileProviderAccountID   string         `json:"file_provider_account_id"`
	FileProviderDisplayName string         `json:"file_provider_display_name"`
	Generation              uint64         `json:"generation"`
}

type MountRoute struct {
	Name       string   `json:"name"`
	TenantID   TenantID `json:"tenant_id"`
	Generation uint64   `json:"generation"`
}

type Quarantine struct {
	Lane          QuarantineLane  `json:"lane"`
	Revision      uint64          `json:"revision"`
	Cause         QuarantineCause `json:"cause"`
	Detail        string          `json:"detail"`
	SinceUnixNano int64           `json:"since_unix_nano"`
}

type TenantState struct {
	OwnerID             OwnerID     `json:"owner_id"`
	TenantID            TenantID    `json:"tenant_id"`
	Generation          uint64      `json:"generation"`
	Requested           uint64      `json:"requested"`
	Desired             uint64      `json:"desired"`
	Observed            uint64      `json:"observed"`
	Verified            uint64      `json:"verified"`
	Applied             uint64      `json:"applied"`
	ActivatedGeneration uint64      `json:"activated_generation"`
	StateVersion        uint64      `json:"state_version"`
	ReplacementEligible bool        `json:"replacement_eligible"`
	Quarantine          *Quarantine `json:"quarantine,omitempty"`
}

type NativeObject struct {
	ID               string     `json:"id"`
	ParentID         string     `json:"parent_id"`
	Name             string     `json:"name"`
	Kind             ObjectKind `json:"kind"`
	Mode             uint32     `json:"mode"`
	Size             int64      `json:"size"`
	Hash             string     `json:"hash"`
	LinkTarget       string     `json:"link_target"`
	Revision         uint64     `json:"revision"`
	MetadataRevision uint64     `json:"metadata_revision"`
	ContentRevision  uint64     `json:"content_revision"`
	Desired          uint64     `json:"desired"`
	Observed         uint64     `json:"observed"`
	Verified         uint64     `json:"verified"`
	Applied          uint64     `json:"applied"`
}

type NativeMountProof struct {
	PresentationRoot string `json:"presentation_root"`
	Filesystem       string `json:"filesystem"`
	Source           string `json:"source"`
	RootReadEpoch    uint64 `json:"root_read_epoch"`
}

type NativeMountIdentity struct {
	PresentationRoot string `json:"presentation_root"`
	Filesystem       string `json:"filesystem"`
	Source           string `json:"source"`
}

type RuntimeHealthRequest struct {
	Protocol uint16 `json:"protocol"`
}

type RuntimeHealthResponse struct {
	Protocol             uint16            `json:"protocol"`
	Code                 ErrorCode         `json:"code"`
	Message              string            `json:"message"`
	RuntimeBuild         string            `json:"runtime_build"`
	ActivationGeneration string            `json:"activation_generation"`
	ReadinessPhase       ReadinessPhase    `json:"readiness_phase"`
	ReadinessStep        ReadinessStep     `json:"readiness_step"`
	NativePhase          NativePhase       `json:"native_phase"`
	NativeMount          *NativeMountProof `json:"native_mount,omitempty"`
	BrokerPhase          BrokerPhase       `json:"broker_phase"`
}

type ProvisionTenantRequest struct {
	Protocol   uint16           `json:"protocol"`
	Definition TenantDefinition `json:"definition"`
}

type ProvisionTenantResponse struct {
	Protocol   uint16    `json:"protocol"`
	Code       ErrorCode `json:"code"`
	Message    string    `json:"message"`
	TenantID   TenantID  `json:"tenant_id"`
	Generation uint64    `json:"generation"`
}

type ReplaceTenantRequest struct {
	Protocol           uint16           `json:"protocol"`
	ExpectedGeneration uint64           `json:"expected_generation"`
	Definition         TenantDefinition `json:"definition"`
}

type ReplaceTenantResponse struct {
	Protocol   uint16    `json:"protocol"`
	Code       ErrorCode `json:"code"`
	Message    string    `json:"message"`
	TenantID   TenantID  `json:"tenant_id"`
	Generation uint64    `json:"generation"`
}

type RemoveTenantRequest struct {
	Protocol   uint16 `json:"protocol"`
	Generation uint64 `json:"generation"`
}

type RemoveTenantResponse struct {
	Protocol           uint16    `json:"protocol"`
	Code               ErrorCode `json:"code"`
	Message            string    `json:"message"`
	TenantID           TenantID  `json:"tenant_id"`
	Generation         uint64    `json:"generation"`
	FileProviderAbsent bool      `json:"file_provider_absent"`
}

type StateRequest struct {
	Protocol uint16 `json:"protocol"`
}

type StateResponse struct {
	Protocol uint16       `json:"protocol"`
	Code     ErrorCode    `json:"code"`
	Message  string       `json:"message"`
	State    *TenantState `json:"state,omitempty"`
}

type NativeBindRequest struct {
	Protocol uint16 `json:"protocol"`
}

type NativeBindResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}

type NativeMountedRequest struct {
	Protocol   uint16              `json:"protocol"`
	Mount      NativeMountIdentity `json:"mount"`
	ProbeToken string              `json:"probe_token"`
}

type NativeMountedResponse struct {
	Protocol   uint16    `json:"protocol"`
	Code       ErrorCode `json:"code"`
	Message    string    `json:"message"`
	ProbeToken string    `json:"probe_token"`
}

type NativeReadyRequest struct {
	Protocol uint16           `json:"protocol"`
	Mount    NativeMountProof `json:"mount"`
}

type NativeReadyResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}

type NativeUnbindRequest struct {
	Protocol uint16 `json:"protocol"`
}

type NativeUnbindResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}

type NativeRoutePageRequest struct {
	Protocol uint16 `json:"protocol"`
	Snapshot uint64 `json:"snapshot"`
	After    string `json:"after"`
	Limit    uint16 `json:"limit"`
}

type NativeRoutePageResponse struct {
	Protocol uint16       `json:"protocol"`
	Code     ErrorCode    `json:"code"`
	Message  string       `json:"message"`
	Snapshot uint64       `json:"snapshot"`
	Routes   []MountRoute `json:"routes"`
	Next     string       `json:"next"`
}

type NativePinRequest struct {
	Protocol uint16 `json:"protocol"`
	Name     string `json:"name"`
}

type NativePinResponse struct {
	Protocol   uint16            `json:"protocol"`
	Code       ErrorCode         `json:"code"`
	Message    string            `json:"message"`
	Token      string            `json:"token"`
	OwnerID    OwnerID           `json:"owner_id"`
	Route      *MountRoute       `json:"route,omitempty"`
	Definition *TenantDefinition `json:"definition,omitempty"`
}

type NativeReleaseRequest struct {
	Protocol uint16 `json:"protocol"`
	Token    string `json:"token"`
}

type NativeReleaseResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Token    string    `json:"token"`
}

type NativeSnapshotOpenRequest struct {
	Protocol   uint16   `json:"protocol"`
	TenantID   TenantID `json:"tenant_id"`
	Generation uint64   `json:"generation"`
	ObjectID   string   `json:"object_id"`
	Revision   uint64   `json:"revision"`
}

type NativeSnapshotOpenResponse struct {
	Protocol uint16        `json:"protocol"`
	Code     ErrorCode     `json:"code"`
	Message  string        `json:"message"`
	Handle   string        `json:"handle"`
	Object   *NativeObject `json:"object,omitempty"`
}

type NativeSnapshotReadRequest struct {
	Protocol uint16 `json:"protocol"`
	Handle   string `json:"handle"`
	Offset   int64  `json:"offset"`
	Length   uint32 `json:"length"`
}

type NativeSnapshotReadResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Data     []byte    `json:"data"`
	EOF      bool      `json:"eof"`
}

type NativeSnapshotCloseRequest struct {
	Protocol uint16 `json:"protocol"`
	Handle   string `json:"handle"`
}

type NativeSnapshotCloseResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Handle   string    `json:"handle"`
}

type NativeWriteOpenRequest struct {
	Protocol   uint16   `json:"protocol"`
	TenantID   TenantID `json:"tenant_id"`
	Generation uint64   `json:"generation"`
	ObjectID   string   `json:"object_id"`
	Revision   uint64   `json:"revision"`
}

type NativeWriteOpenResponse struct {
	Protocol uint16        `json:"protocol"`
	Code     ErrorCode     `json:"code"`
	Message  string        `json:"message"`
	Handle   string        `json:"handle"`
	Object   *NativeObject `json:"object,omitempty"`
}

type NativeWriteReadRequest struct {
	Protocol uint16 `json:"protocol"`
	Handle   string `json:"handle"`
	Offset   int64  `json:"offset"`
	Length   uint32 `json:"length"`
}

type NativeWriteReadResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Data     []byte    `json:"data"`
	EOF      bool      `json:"eof"`
}

type NativeWriteWriteRequest struct {
	Protocol uint16 `json:"protocol"`
	Handle   string `json:"handle"`
	Offset   int64  `json:"offset"`
	Data     []byte `json:"data"`
}

type NativeWriteWriteResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Written  uint32    `json:"written"`
}

type NativeWriteTruncateRequest struct {
	Protocol uint16 `json:"protocol"`
	Handle   string `json:"handle"`
	Size     int64  `json:"size"`
}

type NativeWriteTruncateResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Size     int64     `json:"size"`
}

type NativeWriteSyncRequest struct {
	Protocol uint16 `json:"protocol"`
	Handle   string `json:"handle"`
}

type NativeWriteSyncResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Handle   string    `json:"handle"`
}

type NativeWriteCommitRequest struct {
	Protocol uint16 `json:"protocol"`
	Handle   string `json:"handle"`
}

type NativeWriteCommitResponse struct {
	Protocol   uint16        `json:"protocol"`
	Code       ErrorCode     `json:"code"`
	Message    string        `json:"message"`
	Handle     string        `json:"handle"`
	MutationID MutationID    `json:"mutation_id"`
	Object     *NativeObject `json:"object,omitempty"`
}

type NativeWriteAbortRequest struct {
	Protocol uint16 `json:"protocol"`
	Handle   string `json:"handle"`
}

type NativeWriteAbortResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Handle   string    `json:"handle"`
}
