// Code generated by mountproto/gen; DO NOT EDIT.

package mountproto

const Version uint16 = 1
const SchemaFingerprint = "fusekit.mount.8416193773023b1e883e6cec367c3ee39645901f1a1ba34dd9e06ea3903a43e0"

type Operation string

const (
	OperationTenantRegister Operation = "tenant.register"
	OperationTenantReplace  Operation = "tenant.replace"
	OperationTenantRemove   Operation = "tenant.remove"
	OperationTenantState    Operation = "tenant.state"
	OperationNativeBind     Operation = "native.bind"
	OperationNativeReady    Operation = "native.ready"
	OperationNativeRoutes   Operation = "native.routes"
	OperationNativePin      Operation = "native.pin"
	OperationNativeRelease  Operation = "native.release"
)

type ErrorCode string

const (
	ErrorCodeOk             ErrorCode = "ok"
	ErrorCodeInvalidRequest ErrorCode = "invalid_request"
	ErrorCodeUnauthorized   ErrorCode = "unauthorized"
	ErrorCodeNotFound       ErrorCode = "not_found"
	ErrorCodeConflict       ErrorCode = "conflict"
	ErrorCodeQuarantined    ErrorCode = "quarantined"
	ErrorCodeCanceled       ErrorCode = "canceled"
	ErrorCodeUnavailable    ErrorCode = "unavailable"
)

type AccessMode string

const (
	AccessModeReadOnly  AccessMode = "read_only"
	AccessModeReadWrite AccessMode = "read_write"
)

type CasePolicy string

const (
	CasePolicySensitive   CasePolicy = "sensitive"
	CasePolicyInsensitive CasePolicy = "insensitive"
)

type Presentation string

const (
	PresentationMount        Presentation = "mount"
	PresentationFileProvider Presentation = "file_provider"
)

type QuarantineLane string

const (
	QuarantineLaneCatalogMutation QuarantineLane = "catalog_mutation"
	QuarantineLaneMaterialization QuarantineLane = "materialization"
	QuarantineLaneEnumeration     QuarantineLane = "enumeration"
	QuarantineLaneMountLifecycle  QuarantineLane = "mount_lifecycle"
)

type QuarantineCause string

const (
	QuarantineCauseConflict    QuarantineCause = "conflict"
	QuarantineCauseIntegrity   QuarantineCause = "integrity"
	QuarantineCauseUnsettled   QuarantineCause = "unsettled"
	QuarantineCauseUnavailable QuarantineCause = "unavailable"
)

type TenantID string
type OwnerID string

type TenantDefinition struct {
	PresentationRoot string         `json:"presentation_root"`
	BackingRoot      string         `json:"backing_root"`
	ContentSourceID  string         `json:"content_source_id"`
	AccessMode       AccessMode     `json:"access_mode"`
	CasePolicy       CasePolicy     `json:"case_policy"`
	Presentations    []Presentation `json:"presentations"`
	Generation       uint64         `json:"generation"`
}

type MountRoute struct {
	Name       string   `json:"name"`
	TenantID   TenantID `json:"tenant_id"`
	Generation uint64   `json:"generation"`
}

type Quarantine struct {
	Lane          QuarantineLane  `json:"lane"`
	Revision      uint64          `json:"revision"`
	Cause         QuarantineCause `json:"cause"`
	Detail        string          `json:"detail"`
	SinceUnixNano int64           `json:"since_unix_nano"`
}

type TenantState struct {
	TenantID            TenantID    `json:"tenant_id"`
	Generation          uint64      `json:"generation"`
	Requested           uint64      `json:"requested"`
	Desired             uint64      `json:"desired"`
	Observed            uint64      `json:"observed"`
	Verified            uint64      `json:"verified"`
	Applied             uint64      `json:"applied"`
	ActivatedGeneration uint64      `json:"activated_generation"`
	StateVersion        uint64      `json:"state_version"`
	Quarantine          *Quarantine `json:"quarantine,omitempty"`
}

type RegisterTenantRequest struct {
	Protocol   uint16           `json:"protocol"`
	Definition TenantDefinition `json:"definition"`
}

type RegisterTenantResponse struct {
	Protocol   uint16    `json:"protocol"`
	Code       ErrorCode `json:"code"`
	Message    string    `json:"message"`
	TenantID   TenantID  `json:"tenant_id"`
	Generation uint64    `json:"generation"`
}

type ReplaceTenantRequest struct {
	Protocol           uint16           `json:"protocol"`
	ExpectedGeneration uint64           `json:"expected_generation"`
	Definition         TenantDefinition `json:"definition"`
}

type ReplaceTenantResponse struct {
	Protocol   uint16    `json:"protocol"`
	Code       ErrorCode `json:"code"`
	Message    string    `json:"message"`
	TenantID   TenantID  `json:"tenant_id"`
	Generation uint64    `json:"generation"`
}

type RemoveTenantRequest struct {
	Protocol   uint16 `json:"protocol"`
	Generation uint64 `json:"generation"`
}

type RemoveTenantResponse struct {
	Protocol   uint16    `json:"protocol"`
	Code       ErrorCode `json:"code"`
	Message    string    `json:"message"`
	TenantID   TenantID  `json:"tenant_id"`
	Generation uint64    `json:"generation"`
}

type StateRequest struct {
	Protocol   uint16 `json:"protocol"`
	Generation uint64 `json:"generation"`
}

type StateResponse struct {
	Protocol uint16       `json:"protocol"`
	Code     ErrorCode    `json:"code"`
	Message  string       `json:"message"`
	State    *TenantState `json:"state,omitempty"`
}

type NativeBindRequest struct {
	Protocol uint16 `json:"protocol"`
}

type NativeBindResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}

type NativeReadyRequest struct {
	Protocol uint16 `json:"protocol"`
}

type NativeReadyResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}

type NativeRoutesRequest struct {
	Protocol uint16 `json:"protocol"`
}

type NativeRoutesResponse struct {
	Protocol uint16       `json:"protocol"`
	Code     ErrorCode    `json:"code"`
	Message  string       `json:"message"`
	Routes   []MountRoute `json:"routes"`
}

type NativePinRequest struct {
	Protocol uint16 `json:"protocol"`
	Name     string `json:"name"`
}

type NativePinResponse struct {
	Protocol   uint16            `json:"protocol"`
	Code       ErrorCode         `json:"code"`
	Message    string            `json:"message"`
	Token      string            `json:"token"`
	OwnerID    OwnerID           `json:"owner_id"`
	Route      *MountRoute       `json:"route,omitempty"`
	Definition *TenantDefinition `json:"definition,omitempty"`
}

type NativeReleaseRequest struct {
	Protocol uint16 `json:"protocol"`
	Token    string `json:"token"`
}

type NativeReleaseResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Token    string    `json:"token"`
}
