package fusekit

// PassthroughOnly is an optional interface a Config.FS may implement to declare
// it serves ONLY real backing files: every Read and Getattr delegates to a real
// file on disk, with no synthetic, handler-generated content keyed on a fuse
// file handle (fi->fh).
//
// When an FS declares true AND fuse-t's FSKit backend is available on the
// machine (fuset.FSKitAvailable), Mount selects that backend (-o backend=fskit)
// over fuse-t's default NFS backend. This is opt-in by design: the FSKit backend
// does NOT preserve libfuse's fi->fh read semantics — an FS that returns
// handler-generated bytes for a synthetic handle (a merged, injected, or virtual
// file) gets torn or wrong reads under it (proven against cc-pool's merged
// /.claude.json). So an FS that serves ANY synthetic content must not implement
// this interface, or must return false. The safe default — not implementing it —
// keeps the NFS backend, which honors fi->fh.
type PassthroughOnly interface {
	FusePassthroughOnly() bool
}

// passthroughEligible reports whether fs has affirmatively declared itself pure
// passthrough via PassthroughOnly. The default (no marker, or a false return) is
// not eligible, so Mount keeps the safe NFS backend.
func passthroughEligible(fs any) bool {
	d, ok := fs.(PassthroughOnly)
	return ok && d.FusePassthroughOnly()
}
