// Code generated by sourcedriverproto/gen; DO NOT EDIT.

package sourcedriverproto

const (
	SchemaFingerprint = "fusekit.sourcedriver.343e981ddd496136ed27753a5037fac1ccebccfa6cec18467a76db23e65c3306"
	Build             = SchemaFingerprint
)

const (
	Version              uint16 = 1
	MaxPageItems         uint32 = 256
	MaxTargetPageItems   uint32 = 128
	MaxPageBytes         uint32 = 262144
	MaxContentBytes      uint64 = 1073741824
	MaxTargets           uint32 = 10000
	MaxErrorMessageBytes uint32 = 4096
)

type Operation string

const (
	OperationRefresh          Operation = "source.refresh"
	OperationInspectTargetSet Operation = "source.targets.inspect"
	OperationDeclareTargetSet Operation = "source.targets.declare"
	OperationSnapshot         Operation = "source.snapshot"
	OperationChangesSince     Operation = "source.changes_since"
	OperationOpenContent      Operation = "source.content.open"
	OperationApplyMutation    Operation = "source.mutation.apply"
	OperationInspectMutation  Operation = "source.mutation.inspect"
	OperationSettleMutation   Operation = "source.mutation.settle"
)

type ErrorCode string

const (
	ErrorCodeOK               ErrorCode = "ok"
	ErrorCodeInvalidRequest   ErrorCode = "invalid_request"
	ErrorCodeNotFound         ErrorCode = "not_found"
	ErrorCodeSnapshotRequired ErrorCode = "snapshot_required"
	ErrorCodeStaleRevision    ErrorCode = "stale_revision"
	ErrorCodeConflict         ErrorCode = "conflict"
	ErrorCodeIntegrity        ErrorCode = "integrity"
	ErrorCodeCanceled         ErrorCode = "canceled"
	ErrorCodeUnavailable      ErrorCode = "unavailable"
)

type ObjectKind string

const (
	ObjectKindDirectory ObjectKind = "directory"
	ObjectKindFile      ObjectKind = "file"
	ObjectKindSymlink   ObjectKind = "symlink"
)

type ChangeKind string

const (
	ChangeKindDelete ChangeKind = "delete"
	ChangeKindUpsert ChangeKind = "upsert"
)

type MutationState string

const (
	MutationStateNotFound MutationState = "not_found"
	MutationStatePrepared MutationState = "prepared"
	MutationStateApplied  MutationState = "applied"
)

type PageKind string

const (
	PageKindSnapshot PageKind = "snapshot"
	PageKindChanges  PageKind = "changes"
)

type TargetDeclaration struct {
	Tenant     string `json:"tenant"`
	Generation uint64 `json:"generation"`
}

type TargetSetRef struct {
	ID                  string `json:"id"`
	AuthorityGeneration uint64 `json:"authority_generation"`
	TargetEpoch         uint64 `json:"target_epoch"`
	DeclarationDigest   string `json:"declaration_digest"`
	TargetCount         uint64 `json:"target_count"`
	TargetsDigest       string `json:"targets_digest"`
}

type TargetSetState struct {
	Ref            TargetSetRef       `json:"ref"`
	NextPage       uint32             `json:"next_page"`
	DeclaredCount  uint64             `json:"declared_count"`
	After          *TargetDeclaration `json:"after,omitempty"`
	RollingDigest  string             `json:"rolling_digest"`
	LastPageDigest string             `json:"last_page_digest"`
	Complete       bool               `json:"complete"`
}

type TargetSetPage struct {
	Ref            TargetSetRef        `json:"ref"`
	Sequence       uint32              `json:"sequence"`
	Targets        []TargetDeclaration `json:"targets"`
	Complete       bool                `json:"complete"`
	PreviousDigest string              `json:"previous_digest"`
	Digest         string              `json:"digest"`
	PageDigest     string              `json:"page_digest"`
}

type PageCursor struct {
	TargetSet       TargetSetRef `json:"target_set"`
	Kind            PageKind     `json:"kind"`
	From            string       `json:"from"`
	To              string       `json:"to"`
	Page            uint32       `json:"page"`
	Limit           uint32       `json:"limit"`
	AfterTenant     string       `json:"after_tenant"`
	AfterGeneration uint64       `json:"after_generation"`
	AfterSequence   uint64       `json:"after_sequence"`
	After           string       `json:"after"`
	Continuation    string       `json:"continuation"`
	PreviousDigest  string       `json:"previous_digest"`
	Digest          string       `json:"digest"`
}

type ContentRef struct {
	Revision   string `json:"revision"`
	Tenant     string `json:"tenant"`
	Generation uint64 `json:"generation"`
	Object     string `json:"object"`
	Size       int64  `json:"size"`
	Hash       string `json:"hash"`
}

type Projection struct {
	Tenant              string      `json:"tenant"`
	Generation          uint64      `json:"generation"`
	ID                  string      `json:"id"`
	Parent              string      `json:"parent"`
	Name                string      `json:"name"`
	Kind                ObjectKind  `json:"kind"`
	Mode                uint32      `json:"mode"`
	LinkTarget          string      `json:"link_target"`
	MountVisible        bool        `json:"mount_visible"`
	FileProviderVisible bool        `json:"file_provider_visible"`
	Size                int64       `json:"size"`
	Hash                string      `json:"hash"`
	Content             *ContentRef `json:"content,omitempty"`
}

type Change struct {
	Kind       ChangeKind  `json:"kind"`
	Tenant     string      `json:"tenant"`
	Generation uint64      `json:"generation"`
	Sequence   uint64      `json:"sequence"`
	ID         string      `json:"id"`
	Object     *Projection `json:"object,omitempty"`
}

type SourceLocator struct {
	Authority string `json:"authority"`
	Key       string `json:"key"`
	Revision  uint64 `json:"revision"`
}

type MutationOperation struct {
	Kind       uint8  `json:"kind"`
	Name       string `json:"name"`
	ObjectKind uint8  `json:"object_kind"`
	Mode       uint32 `json:"mode"`
	LinkTarget string `json:"link_target"`
	HasContent bool   `json:"has_content"`
}

type MutationContext struct {
	Operation MutationOperation `json:"operation"`
	Object    *SourceLocator    `json:"object,omitempty"`
	Parent    *SourceLocator    `json:"parent,omitempty"`
	Target    *SourceLocator    `json:"target,omitempty"`
}

type MutationReceipt struct {
	OperationID   string        `json:"operation_id"`
	State         MutationState `json:"state"`
	RequestDigest string        `json:"request_digest"`
	Expected      string        `json:"expected"`
	Committed     string        `json:"committed"`
	Result        string        `json:"result"`
	Digest        string        `json:"digest"`
}

type MutationSettlementKind string

const (
	MutationSettlementAcknowledge MutationSettlementKind = "acknowledge"
	MutationSettlementAbandon     MutationSettlementKind = "abandon"
	MutationSettlementForget      MutationSettlementKind = "forget"
)

type MutationSettlement struct {
	TargetSet     TargetSetRef           `json:"target_set"`
	OperationID   string                 `json:"operation_id"`
	RequestDigest string                 `json:"request_digest"`
	ReceiptDigest string                 `json:"receipt_digest"`
	Kind          MutationSettlementKind `json:"kind"`
}

type RefreshRequest struct {
	Protocol uint16 `json:"protocol"`
}

type RefreshResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Revision string    `json:"revision"`
	Actual   string    `json:"actual"`
}

type InspectTargetSetRequest struct {
	Protocol uint16       `json:"protocol"`
	Ref      TargetSetRef `json:"ref"`
}

type InspectTargetSetResponse struct {
	Protocol uint16          `json:"protocol"`
	Code     ErrorCode       `json:"code"`
	Message  string          `json:"message"`
	State    *TargetSetState `json:"state,omitempty"`
}

type DeclareTargetSetRequest struct {
	Protocol uint16        `json:"protocol"`
	Page     TargetSetPage `json:"page"`
}

type DeclareTargetSetResponse struct {
	Protocol uint16          `json:"protocol"`
	Code     ErrorCode       `json:"code"`
	Message  string          `json:"message"`
	State    *TargetSetState `json:"state,omitempty"`
}

type SnapshotRequest struct {
	Protocol  uint16       `json:"protocol"`
	TargetSet TargetSetRef `json:"target_set"`
	Revision  string       `json:"revision"`
	Cursor    *PageCursor  `json:"cursor,omitempty"`
	Limit     uint32       `json:"limit"`
}

type SnapshotResponse struct {
	Protocol uint16       `json:"protocol"`
	Code     ErrorCode    `json:"code"`
	Message  string       `json:"message"`
	Revision string       `json:"revision"`
	Objects  []Projection `json:"objects"`
	Next     *PageCursor  `json:"next,omitempty"`
	Digest   string       `json:"digest"`
	Actual   string       `json:"actual"`
}

type ChangesSinceRequest struct {
	Protocol  uint16       `json:"protocol"`
	TargetSet TargetSetRef `json:"target_set"`
	From      string       `json:"from"`
	To        string       `json:"to"`
	Cursor    *PageCursor  `json:"cursor,omitempty"`
	Limit     uint32       `json:"limit"`
}

type ChangesSinceResponse struct {
	Protocol uint16      `json:"protocol"`
	Code     ErrorCode   `json:"code"`
	Message  string      `json:"message"`
	From     string      `json:"from"`
	To       string      `json:"to"`
	Changes  []Change    `json:"changes"`
	Next     *PageCursor `json:"next,omitempty"`
	Digest   string      `json:"digest"`
	Actual   string      `json:"actual"`
}

type OpenContentRequest struct {
	Protocol uint16     `json:"protocol"`
	Content  ContentRef `json:"content"`
}

type OpenContentResponse struct {
	Protocol uint16      `json:"protocol"`
	Code     ErrorCode   `json:"code"`
	Message  string      `json:"message"`
	Content  *ContentRef `json:"content,omitempty"`
	Actual   string      `json:"actual"`
}

type ApplyMutationRequest struct {
	Protocol    uint16          `json:"protocol"`
	TargetSet   TargetSetRef    `json:"target_set"`
	Tenant      string          `json:"tenant"`
	Generation  uint64          `json:"generation"`
	OperationID string          `json:"operation_id"`
	Expected    string          `json:"expected"`
	Context     MutationContext `json:"context"`
	HasContent  bool            `json:"has_content"`
	ContentSize int64           `json:"content_size"`
	ContentHash string          `json:"content_hash"`
}

type ApplyMutationResponse struct {
	Protocol uint16           `json:"protocol"`
	Code     ErrorCode        `json:"code"`
	Message  string           `json:"message"`
	Receipt  *MutationReceipt `json:"receipt,omitempty"`
	Actual   string           `json:"actual"`
}

type InspectMutationRequest struct {
	Protocol      uint16 `json:"protocol"`
	OperationID   string `json:"operation_id"`
	RequestDigest string `json:"request_digest"`
}

type InspectMutationResponse struct {
	Protocol uint16           `json:"protocol"`
	Code     ErrorCode        `json:"code"`
	Message  string           `json:"message"`
	Receipt  *MutationReceipt `json:"receipt,omitempty"`
}

type SettleMutationRequest struct {
	Protocol   uint16             `json:"protocol"`
	Settlement MutationSettlement `json:"settlement"`
}

type SettleMutationResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}
