// Code generated by transportproto/gen; DO NOT EDIT.

package transportproto

const Version uint16 = 1
const WireBuild = "com.yasyf.fusekit.transport/bb57be1d3dc4e5e0866f676ee11428147e351f6f877772dc96e3a789cc2e9adf/v1"
const CatalogSchemaFingerprint = "fusekit.catalog.c82e6853bbf514796c9283ad1fd80d836ad39fa5cb971b6a7f469fc957f0d6e0"
const CatalogWorkerSchemaFingerprint = "fusekit.catalog-worker.c3951ba3f97d31c5448b3f246d363b824c112444a951d1428bfee8a2731182fd"
const MountSchemaFingerprint = "fusekit.mount.b73d0727dfd1594042dc4d549cab2e893579af70cca0785f3401ec39ae8cc1f4"
const SourceDriverSchemaFingerprint = "fusekit.sourcedriver.343e981ddd496136ed27753a5037fac1ccebccfa6cec18467a76db23e65c3306"
