// Code generated by catalogproto/gen; DO NOT EDIT.

package catalogproto

const Version uint16 = 5
const SchemaFingerprint = "fusekit.catalog.867db61de4f75596b964cb9a71a4f4bdb040e5400683f7b19ffd2d7eb85d2687"

const ChangeCursorCompleteSequence uint32 = ^uint32(0)

type Operation string

const (
	OperationCatalogRoot                 Operation = "catalog.root"
	OperationCatalogHead                 Operation = "catalog.head"
	OperationCatalogSnapshot             Operation = "catalog.snapshot"
	OperationCatalogChangesSince         Operation = "catalog.changes_since"
	OperationCatalogLookup               Operation = "catalog.lookup"
	OperationCatalogLookupName           Operation = "catalog.lookup_name"
	OperationCatalogOpenAt               Operation = "catalog.open_at"
	OperationCatalogMutate               Operation = "catalog.mutate"
	OperationSourceReconcile             Operation = "source.reconcile"
	OperationTenantPrepare               Operation = "tenant.prepare"
	OperationConvergenceAck              Operation = "convergence.ack"
	OperationConvergenceNotify           Operation = "convergence.notify"
	OperationBrokerOpen                  Operation = "broker.open"
	OperationBrokerBindDomain            Operation = "broker.bind_domain"
	OperationBrokerForward               Operation = "broker.forward"
	OperationBrokerProvePeer             Operation = "broker.prove_peer"
	OperationBrokerCutoverDomains        Operation = "broker.cutover_domains"
	OperationBrokerClaimCutover          Operation = "broker.claim_cutover"
	OperationBrokerRecoverCutoverClaim   Operation = "broker.recover_cutover_claim"
	OperationBrokerRecoverCutoverReceipt Operation = "broker.recover_cutover_receipt"
)

type ErrorCode string

const (
	ErrorCodeOk             ErrorCode = "ok"
	ErrorCodeInvalidRequest ErrorCode = "invalid_request"
	ErrorCodeStaleAnchor    ErrorCode = "stale_anchor"
	ErrorCodeNotFound       ErrorCode = "not_found"
	ErrorCodeConflict       ErrorCode = "conflict"
	ErrorCodeQuarantined    ErrorCode = "quarantined"
	ErrorCodeIntegrity      ErrorCode = "integrity"
	ErrorCodeExpired        ErrorCode = "expired"
	ErrorCodeUnavailable    ErrorCode = "unavailable"
)

type ObjectKind string

const (
	ObjectKindDirectory ObjectKind = "directory"
	ObjectKindFile      ObjectKind = "file"
	ObjectKindSymlink   ObjectKind = "symlink"
)

type ChangeKind string

const (
	ChangeKindDelete ChangeKind = "delete"
	ChangeKindUpsert ChangeKind = "upsert"
)

type MutationKind string

const (
	MutationKindCreate  MutationKind = "create"
	MutationKindRevise  MutationKind = "revise"
	MutationKindDelete  MutationKind = "delete"
	MutationKindReplace MutationKind = "replace"
)

type SourceMode string

const (
	SourceModeSnapshot SourceMode = "snapshot"
	SourceModeDelta    SourceMode = "delta"
)

type ConvergenceCause string

const (
	ConvergenceCauseProviderMutation     ConvergenceCause = "provider_mutation"
	ConvergenceCauseDaemonWrite          ConvergenceCause = "daemon_write"
	ConvergenceCauseExternalUnattributed ConvergenceCause = "external_unattributed"
	ConvergenceCauseMigration            ConvergenceCause = "migration"
	ConvergenceCauseOnDemand             ConvergenceCause = "on_demand"
)

type SignalTargetKind string

const (
	SignalTargetKindWorkingSet SignalTargetKind = "working_set"
	SignalTargetKindContainer  SignalTargetKind = "container"
)

type EnumerationScopeKind string

const (
	EnumerationScopeKindWorkingSet EnumerationScopeKind = "working_set"
	EnumerationScopeKindContainer  EnumerationScopeKind = "container"
)

type BrokerCommandKind string

const (
	BrokerCommandKindRegisterDomain BrokerCommandKind = "register_domain"
	BrokerCommandKindRemoveDomain   BrokerCommandKind = "remove_domain"
	BrokerCommandKindListDomains    BrokerCommandKind = "list_domains"
	BrokerCommandKindSignalDomain   BrokerCommandKind = "signal_domain"
	BrokerCommandKindCutoverDomains BrokerCommandKind = "cutover_domains"
)

type ObjectID string
type MutationID string

type TenantID string
type DomainID string
type OwnerID string
type AccountInstanceID string
type SourceAuthorityID string
type ChangeID string

type CatalogObject struct {
	ID               ObjectID   `json:"id"`
	ParentID         ObjectID   `json:"parent_id"`
	Revision         uint64     `json:"revision"`
	MetadataRevision uint64     `json:"metadata_revision"`
	ContentRevision  uint64     `json:"content_revision"`
	Name             string     `json:"name"`
	Kind             ObjectKind `json:"kind"`
	Mode             uint32     `json:"mode"`
	Size             uint64     `json:"size"`
	Hash             string     `json:"hash"`
	LinkTarget       string     `json:"link_target"`
	Desired          uint64     `json:"desired"`
	Observed         uint64     `json:"observed"`
	Verified         uint64     `json:"verified"`
	Applied          uint64     `json:"applied"`
	Tombstone        bool       `json:"tombstone"`
}

type Change struct {
	Revision uint64        `json:"revision"`
	Sequence uint32        `json:"sequence"`
	Kind     ChangeKind    `json:"kind"`
	Object   CatalogObject `json:"object"`
}

type ChangeCursor struct {
	Revision uint64 `json:"revision"`
	Sequence uint32 `json:"sequence"`
}

type CatalogLaneProof struct {
	Tenant     TenantID `json:"tenant"`
	Generation uint64   `json:"generation"`
	Requested  uint64   `json:"requested"`
	Desired    uint64   `json:"desired"`
	Observed   uint64   `json:"observed"`
	Verified   uint64   `json:"verified"`
	Applied    uint64   `json:"applied"`
}

type DomainObservation struct {
	TenantID          TenantID          `json:"tenant_id"`
	DomainID          DomainID          `json:"domain_id"`
	Generation        uint64            `json:"generation"`
	RequestedRevision uint64            `json:"requested_revision"`
	ObservedRevision  uint64            `json:"observed_revision"`
	CatalogRevision   uint64            `json:"catalog_revision"`
	SourceAuthority   SourceAuthorityID `json:"source_authority"`
	SourceRevision    uint64            `json:"source_revision"`
	ChangeID          ChangeID          `json:"change_id"`
	OperationID       MutationID        `json:"operation_id"`
}

type PreparationProof struct {
	Catalog CatalogLaneProof  `json:"catalog"`
	Domain  DomainObservation `json:"domain"`
}

type SignalTarget struct {
	Kind     SignalTargetKind `json:"kind"`
	ParentID *ObjectID        `json:"parent_id,omitempty"`
}

type EnumerationScope struct {
	Kind     EnumerationScopeKind `json:"kind"`
	ParentID *ObjectID            `json:"parent_id,omitempty"`
}

type BrokerForwardContext struct {
	DomainID   DomainID `json:"domain_id"`
	TenantID   TenantID `json:"tenant_id"`
	Generation uint64   `json:"generation"`
}

type ConvergenceNotification struct {
	Protocol        uint16            `json:"protocol"`
	TenantID        TenantID          `json:"tenant_id"`
	DomainID        DomainID          `json:"domain_id"`
	Generation      uint64            `json:"generation"`
	Revision        uint64            `json:"revision"`
	CatalogRevision uint64            `json:"catalog_revision"`
	SourceAuthority SourceAuthorityID `json:"source_authority"`
	SourceRevision  uint64            `json:"source_revision"`
	ChangeID        ChangeID          `json:"change_id"`
	OperationID     MutationID        `json:"operation_id"`
	Cause           ConvergenceCause  `json:"cause"`
	AffectedKeys    []string          `json:"affected_keys"`
	Targets         []SignalTarget    `json:"targets"`
}

type DomainRegistration struct {
	DomainID          DomainID          `json:"domain_id"`
	OwnerID           OwnerID           `json:"owner_id"`
	TenantID          TenantID          `json:"tenant_id"`
	Generation        uint64            `json:"generation"`
	RootID            ObjectID          `json:"root_id"`
	AccountInstanceID AccountInstanceID `json:"account_instance_id"`
	DisplayName       string            `json:"display_name"`
}

type RegisteredDomain struct {
	DomainID          DomainID          `json:"domain_id"`
	OwnerID           OwnerID           `json:"owner_id"`
	TenantID          TenantID          `json:"tenant_id"`
	Generation        uint64            `json:"generation"`
	RootID            ObjectID          `json:"root_id"`
	AccountInstanceID AccountInstanceID `json:"account_instance_id"`
	DisplayName       string            `json:"display_name"`
	PublicPath        string            `json:"public_path"`
}

type DomainCutoverAccount struct {
	AccountID         uint64             `json:"account_id"`
	ImmutableIdentity string             `json:"immutable_identity"`
	LegacyDomainID    string             `json:"legacy_domain_id"`
	AccountInstanceID *AccountInstanceID `json:"account_instance_id,omitempty"`
}

type DomainCutoverPlan struct {
	OperationID MutationID             `json:"operation_id"`
	OwnerID     OwnerID                `json:"owner_id"`
	Accounts    []DomainCutoverAccount `json:"accounts"`
}

type DomainCutoverRecoveryAccount struct {
	AccountID         uint64 `json:"account_id"`
	ImmutableIdentity string `json:"immutable_identity"`
}

type DomainCutoverRecoveryKey struct {
	OwnerID  OwnerID                        `json:"owner_id"`
	Accounts []DomainCutoverRecoveryAccount `json:"accounts"`
}

type DomainCutoverObservation struct {
	DomainID          string             `json:"domain_id"`
	AccountID         uint64             `json:"account_id"`
	ImmutableIdentity string             `json:"immutable_identity"`
	Generation        uint64             `json:"generation"`
	AccountInstanceID *AccountInstanceID `json:"account_instance_id,omitempty"`
	Legacy            bool               `json:"legacy"`
}

type DomainCutoverResult struct {
	Plan                      DomainCutoverPlan          `json:"plan"`
	ObservedDomains           []DomainCutoverObservation `json:"observed_domains"`
	FinalEnumerationRevision  uint64                     `json:"final_enumeration_revision"`
	FinalEnumeratedAtUnixNano int64                      `json:"final_enumerated_at_unix_nano"`
}

type DomainAbsenceProof struct {
	Result                            DomainCutoverResult `json:"result"`
	BrokerProductBuild                string              `json:"broker_product_build"`
	BrokerPID                         int64               `json:"broker_pid"`
	BrokerUID                         int64               `json:"broker_uid"`
	BrokerStartTime                   string              `json:"broker_start_time"`
	BrokerBoot                        string              `json:"broker_boot"`
	BrokerComm                        string              `json:"broker_comm"`
	BrokerExecutable                  string              `json:"broker_executable"`
	BrokerDesignatedRequirement       string              `json:"broker_designated_requirement"`
	BrokerAuditTokenDigest            string              `json:"broker_audit_token_digest"`
	BrokerEntitlementValidationDigest string              `json:"broker_entitlement_validation_digest"`
}

type BrokerPeerProof struct {
	BrokerProductBuild                string `json:"broker_product_build"`
	BrokerPID                         int64  `json:"broker_pid"`
	BrokerUID                         int64  `json:"broker_uid"`
	BrokerStartTime                   string `json:"broker_start_time"`
	BrokerBoot                        string `json:"broker_boot"`
	BrokerComm                        string `json:"broker_comm"`
	BrokerExecutable                  string `json:"broker_executable"`
	BrokerDesignatedRequirement       string `json:"broker_designated_requirement"`
	BrokerAuditTokenDigest            string `json:"broker_audit_token_digest"`
	BrokerEntitlementValidationDigest string `json:"broker_entitlement_validation_digest"`
}

type DomainCutoverClaim struct {
	OperationID       MutationID `json:"operation_id"`
	ProofDigest       string     `json:"proof_digest"`
	ClaimedAtUnixNano int64      `json:"claimed_at_unix_nano"`
}

type DomainCutoverReceipt struct {
	Proof DomainAbsenceProof `json:"proof"`
	Claim DomainCutoverClaim `json:"claim"`
}

type BrokerOpenRequest struct {
	Protocol uint16 `json:"protocol"`
}

type BrokerOpenResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}

type BrokerBindDomainRequest struct {
	Protocol   uint16   `json:"protocol"`
	DomainID   DomainID `json:"domain_id"`
	TenantID   TenantID `json:"tenant_id"`
	Generation uint64   `json:"generation"`
}

type BrokerBindDomainResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}

type BrokerForwardRequest struct {
	Protocol  uint16               `json:"protocol"`
	Context   BrokerForwardContext `json:"context"`
	Operation Operation            `json:"operation"`
	Payload   []byte               `json:"payload"`
}

type BrokerCommand struct {
	Protocol     uint16                   `json:"protocol"`
	CommandID    uint64                   `json:"command_id"`
	Kind         BrokerCommandKind        `json:"kind"`
	Registration *DomainRegistration      `json:"registration,omitempty"`
	DomainID     *DomainID                `json:"domain_id,omitempty"`
	Notification *ConvergenceNotification `json:"notification,omitempty"`
	Cutover      *DomainCutoverPlan       `json:"cutover,omitempty"`
}

type BrokerResult struct {
	Protocol        uint16               `json:"protocol"`
	Code            ErrorCode            `json:"code"`
	Message         string               `json:"message"`
	CommandID       uint64               `json:"command_id"`
	Kind            BrokerCommandKind    `json:"kind"`
	Registered      *RegisteredDomain    `json:"registered,omitempty"`
	ConfirmedAbsent *bool                `json:"confirmed_absent,omitempty"`
	Domains         *[]RegisteredDomain  `json:"domains,omitempty"`
	SignalAccepted  *bool                `json:"signal_accepted,omitempty"`
	CutoverResult   *DomainCutoverResult `json:"cutover_result,omitempty"`
}

type CutoverDomainsRequest struct {
	Protocol uint16            `json:"protocol"`
	Plan     DomainCutoverPlan `json:"plan"`
}

type CutoverDomainsResponse struct {
	Protocol uint16              `json:"protocol"`
	Code     ErrorCode           `json:"code"`
	Message  string              `json:"message"`
	Proof    *DomainAbsenceProof `json:"proof,omitempty"`
}

type ClaimDomainCutoverRequest struct {
	Protocol uint16             `json:"protocol"`
	Proof    DomainAbsenceProof `json:"proof"`
}

type ClaimDomainCutoverResponse struct {
	Protocol uint16              `json:"protocol"`
	Code     ErrorCode           `json:"code"`
	Message  string              `json:"message"`
	Claim    *DomainCutoverClaim `json:"claim,omitempty"`
}

type RecoverDomainCutoverClaimRequest struct {
	Protocol uint16             `json:"protocol"`
	Proof    DomainAbsenceProof `json:"proof"`
}

type RecoverDomainCutoverClaimResponse struct {
	Protocol uint16              `json:"protocol"`
	Code     ErrorCode           `json:"code"`
	Message  string              `json:"message"`
	Claim    *DomainCutoverClaim `json:"claim,omitempty"`
}

type RecoverDomainCutoverReceiptRequest struct {
	Protocol uint16                   `json:"protocol"`
	Key      DomainCutoverRecoveryKey `json:"key"`
}

type RecoverDomainCutoverReceiptResponse struct {
	Protocol uint16                `json:"protocol"`
	Code     ErrorCode             `json:"code"`
	Message  string                `json:"message"`
	Receipt  *DomainCutoverReceipt `json:"receipt,omitempty"`
}

type ProveBrokerPeerRequest struct {
	Protocol uint16 `json:"protocol"`
}

type ProveBrokerPeerResponse struct {
	Protocol uint16           `json:"protocol"`
	Code     ErrorCode        `json:"code"`
	Message  string           `json:"message"`
	Proof    *BrokerPeerProof `json:"proof,omitempty"`
}

type RootRequest struct {
	Protocol   uint16 `json:"protocol"`
	Generation uint64 `json:"generation"`
}

type HeadRequest struct {
	Protocol   uint16 `json:"protocol"`
	Generation uint64 `json:"generation"`
}

type HeadResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Revision uint64    `json:"revision"`
}

type SnapshotRequest struct {
	Protocol   uint16           `json:"protocol"`
	Generation uint64           `json:"generation"`
	Revision   uint64           `json:"revision"`
	Scope      EnumerationScope `json:"scope"`
	After      *ObjectID        `json:"after,omitempty"`
	Limit      uint32           `json:"limit"`
}

type SnapshotResponse struct {
	Protocol uint16          `json:"protocol"`
	Code     ErrorCode       `json:"code"`
	Message  string          `json:"message"`
	Revision uint64          `json:"revision"`
	Objects  []CatalogObject `json:"objects"`
	Next     *ObjectID       `json:"next,omitempty"`
}

type ChangesSinceRequest struct {
	Protocol   uint16           `json:"protocol"`
	Generation uint64           `json:"generation"`
	Cursor     ChangeCursor     `json:"cursor"`
	Scope      EnumerationScope `json:"scope"`
	Limit      uint32           `json:"limit"`
}

type ChangesSinceResponse struct {
	Protocol uint16       `json:"protocol"`
	Code     ErrorCode    `json:"code"`
	Message  string       `json:"message"`
	Floor    uint64       `json:"floor"`
	Head     uint64       `json:"head"`
	Next     ChangeCursor `json:"next"`
	Complete bool         `json:"complete"`
	Changes  []Change     `json:"changes"`
}

type LookupRequest struct {
	Protocol   uint16   `json:"protocol"`
	Generation uint64   `json:"generation"`
	ObjectID   ObjectID `json:"object_id"`
}

type LookupNameRequest struct {
	Protocol   uint16   `json:"protocol"`
	Generation uint64   `json:"generation"`
	ParentID   ObjectID `json:"parent_id"`
	Name       string   `json:"name"`
}

type LookupResponse struct {
	Protocol uint16         `json:"protocol"`
	Code     ErrorCode      `json:"code"`
	Message  string         `json:"message"`
	Object   *CatalogObject `json:"object,omitempty"`
}

type OpenAtRequest struct {
	Protocol   uint16   `json:"protocol"`
	Generation uint64   `json:"generation"`
	ObjectID   ObjectID `json:"object_id"`
	Revision   uint64   `json:"revision"`
}

type OpenAtResponse struct {
	Protocol uint16         `json:"protocol"`
	Code     ErrorCode      `json:"code"`
	Message  string         `json:"message"`
	Object   *CatalogObject `json:"object,omitempty"`
}

type MutationRequest struct {
	Protocol         uint16       `json:"protocol"`
	OperationID      MutationID   `json:"operation_id"`
	Generation       uint64       `json:"generation"`
	ExpectedRevision uint64       `json:"expected_revision"`
	Kind             MutationKind `json:"kind"`
	ObjectKind       *ObjectKind  `json:"object_kind,omitempty"`
	HasContent       bool         `json:"has_content"`
	ObjectID         *ObjectID    `json:"object_id,omitempty"`
	ParentID         *ObjectID    `json:"parent_id,omitempty"`
	TargetID         *ObjectID    `json:"target_id,omitempty"`
	Name             *string      `json:"name,omitempty"`
	Mode             *uint32      `json:"mode,omitempty"`
	ContentRevision  *uint64      `json:"content_revision,omitempty"`
	LinkTarget       *string      `json:"link_target,omitempty"`
}

type MutationResponse struct {
	Protocol    uint16      `json:"protocol"`
	Code        ErrorCode   `json:"code"`
	Message     string      `json:"message"`
	OperationID *MutationID `json:"operation_id,omitempty"`
	Revision    uint64      `json:"revision"`
	PrimaryID   *ObjectID   `json:"primary_id,omitempty"`
	SecondaryID *ObjectID   `json:"secondary_id,omitempty"`
}

type SourceCommit struct {
	TenantID        TenantID `json:"tenant_id"`
	CatalogRevision uint64   `json:"catalog_revision"`
}

type SourceTenantRecord struct {
	TenantID    TenantID `json:"tenant_id"`
	Generation  uint64   `json:"generation"`
	RootKey     string   `json:"root_key"`
	ObjectCount uint32   `json:"object_count"`
	DeleteCount uint32   `json:"delete_count"`
}

type SourceObjectRecord struct {
	SourceKey           string     `json:"source_key"`
	ParentKey           string     `json:"parent_key"`
	Name                string     `json:"name"`
	Kind                ObjectKind `json:"kind"`
	Mode                uint32     `json:"mode"`
	ContentRevision     uint64     `json:"content_revision"`
	Size                uint64     `json:"size"`
	Hash                string     `json:"hash"`
	LinkTarget          string     `json:"link_target"`
	MountVisible        bool       `json:"mount_visible"`
	FileProviderVisible bool       `json:"file_provider_visible"`
}

type SourceDeleteRecord struct {
	SourceKey string `json:"source_key"`
}

type SourceReconcileRequest struct {
	Protocol            uint16            `json:"protocol"`
	Mode                SourceMode        `json:"mode"`
	SourceAuthority     SourceAuthorityID `json:"source_authority"`
	SourceRevision      uint64            `json:"source_revision"`
	PredecessorRevision uint64            `json:"predecessor_revision"`
	ChangeID            ChangeID          `json:"change_id"`
	OperationID         MutationID        `json:"operation_id"`
	Cause               ConvergenceCause  `json:"cause"`
	OriginDomain        DomainID          `json:"origin_domain"`
	OriginGeneration    uint64            `json:"origin_generation"`
	AffectedKeys        []string          `json:"affected_keys"`
	TenantCount         uint32            `json:"tenant_count"`
}

type SourceReconcileResponse struct {
	Protocol        uint16            `json:"protocol"`
	Code            ErrorCode         `json:"code"`
	Message         string            `json:"message"`
	SourceAuthority SourceAuthorityID `json:"source_authority"`
	SourceRevision  uint64            `json:"source_revision"`
	ChangeID        ChangeID          `json:"change_id"`
	OperationID     MutationID        `json:"operation_id"`
	Commits         []SourceCommit    `json:"commits"`
}

type PrepareTenantRequest struct {
	Protocol        uint16            `json:"protocol"`
	DomainID        DomainID          `json:"domain_id"`
	Generation      uint64            `json:"generation"`
	CatalogRevision uint64            `json:"catalog_revision"`
	SourceAuthority SourceAuthorityID `json:"source_authority"`
	SourceRevision  uint64            `json:"source_revision"`
	ChangeID        ChangeID          `json:"change_id"`
	OperationID     MutationID        `json:"operation_id"`
}

type PrepareTenantResponse struct {
	Protocol uint16            `json:"protocol"`
	Code     ErrorCode         `json:"code"`
	Message  string            `json:"message"`
	Proof    *PreparationProof `json:"proof,omitempty"`
}

type AckConvergenceRequest struct {
	Protocol        uint16            `json:"protocol"`
	DomainID        DomainID          `json:"domain_id"`
	Generation      uint64            `json:"generation"`
	Revision        uint64            `json:"revision"`
	CatalogRevision uint64            `json:"catalog_revision"`
	SourceAuthority SourceAuthorityID `json:"source_authority"`
	SourceRevision  uint64            `json:"source_revision"`
	ChangeID        ChangeID          `json:"change_id"`
	OperationID     MutationID        `json:"operation_id"`
}

type AckConvergenceResponse struct {
	Protocol    uint16             `json:"protocol"`
	Code        ErrorCode          `json:"code"`
	Message     string             `json:"message"`
	Observation *DomainObservation `json:"observation,omitempty"`
}
