// Code generated by catalogproto/gen; DO NOT EDIT.

package catalogproto

const Version uint16 = 1
const MaxPageSize uint32 = 1000
const MaxSignalTargets uint32 = 64
const MaxNameBytes uint32 = 255
const MaxBrokerDomainPageSize uint32 = 16
const MaxObservedDomainIdentifierBytes uint32 = 4096
const MaxObservedDomainIDBytes uint32 = 5468
const MaxBrokerForwardPayloadBytes uint32 = 1048576
const MaxErrorMessageBytes uint32 = 4096
const MaxDisplayNameBytes uint32 = 255
const MaxPublicPathBytes uint32 = 4096
const MaxSourceFleetDeclarations uint32 = 256
const MaxSourceFleetBytes uint32 = 1048576
const MaxSourceDriverIDBytes uint32 = 128
const MaxSourceDriverConfigBytes uint32 = 65536
const MaxBackingStoreIdentityBytes uint32 = 256
const SchemaFingerprint = "fusekit.catalog.013823ad85dc15dd522019e5b0a8d04219bb40d87321ade4c1aa416d5f05d5db"

const ChangeCursorCompleteSequence uint32 = ^uint32(0)

type Operation string

const (
	OperationCatalogRoot                        Operation = "catalog.root"
	OperationCatalogHead                        Operation = "catalog.head"
	OperationCatalogSnapshot                    Operation = "catalog.snapshot"
	OperationCatalogChangesSince                Operation = "catalog.changes_since"
	OperationCatalogLookup                      Operation = "catalog.lookup"
	OperationCatalogLookupName                  Operation = "catalog.lookup_name"
	OperationCatalogOpenAt                      Operation = "catalog.open_at"
	OperationCatalogMutate                      Operation = "catalog.mutate"
	OperationTenantPrepare                      Operation = "tenant.prepare"
	OperationPresentationLeaseCommit            Operation = "presentation_lease.commit"
	OperationPresentationLeaseRenew             Operation = "presentation_lease.renew"
	OperationPresentationLeaseRelease           Operation = "presentation_lease.release"
	OperationActivationAck                      Operation = "activation.ack"
	OperationActivationNotify                   Operation = "activation.notify"
	OperationMaterializationSnapshotBegin       Operation = "materialization.snapshot.begin"
	OperationMaterializationSnapshotSuspend     Operation = "materialization.snapshot.suspend"
	OperationMaterializationSnapshotStagePage   Operation = "materialization.snapshot.stage_page"
	OperationMaterializationSnapshotCommit      Operation = "materialization.snapshot.commit"
	OperationSourceAuthorityPublishDesiredFleet Operation = "source_authority.publish_desired_fleet"
	OperationSourceAuthorityReadDesiredFleet    Operation = "source_authority.read_desired_fleet"
	OperationBrokerOpen                         Operation = "broker.open"
	OperationBrokerForward                      Operation = "broker.forward"
)

type ErrorCode string

const (
	ErrorCodeOk             ErrorCode = "ok"
	ErrorCodeInvalidRequest ErrorCode = "invalid_request"
	ErrorCodeStaleAnchor    ErrorCode = "stale_anchor"
	ErrorCodeNotFound       ErrorCode = "not_found"
	ErrorCodeConflict       ErrorCode = "conflict"
	ErrorCodeQuarantined    ErrorCode = "quarantined"
	ErrorCodeIntegrity      ErrorCode = "integrity"
	ErrorCodeExpired        ErrorCode = "expired"
	ErrorCodeUnavailable    ErrorCode = "unavailable"
)

type ObjectKind string

const (
	ObjectKindDirectory ObjectKind = "directory"
	ObjectKindFile      ObjectKind = "file"
	ObjectKindSymlink   ObjectKind = "symlink"
)

type ChangeKind string

const (
	ChangeKindDelete ChangeKind = "delete"
	ChangeKindUpsert ChangeKind = "upsert"
)

type MutationKind string

const (
	MutationKindCreate  MutationKind = "create"
	MutationKindRevise  MutationKind = "revise"
	MutationKindDelete  MutationKind = "delete"
	MutationKindReplace MutationKind = "replace"
)

type ActivationCause string

const (
	ActivationCauseProviderMutation     ActivationCause = "provider_mutation"
	ActivationCauseDaemonWrite          ActivationCause = "daemon_write"
	ActivationCauseExternalUnattributed ActivationCause = "external_unattributed"
	ActivationCauseBootstrap            ActivationCause = "bootstrap"
)

type SignalTargetKind string

const (
	SignalTargetKindWorkingSet SignalTargetKind = "working_set"
	SignalTargetKindContainer  SignalTargetKind = "container"
)

type EnumerationScopeKind string

const (
	EnumerationScopeKindWorkingSet EnumerationScopeKind = "working_set"
	EnumerationScopeKindContainer  EnumerationScopeKind = "container"
)

type TenantAccessMode string

const (
	TenantAccessModeReadOnly  TenantAccessMode = "read_only"
	TenantAccessModeReadWrite TenantAccessMode = "read_write"
)

type PresentationKind string

const (
	PresentationKindMount        PresentationKind = "mount"
	PresentationKindFileProvider PresentationKind = "file_provider"
)

type FileProviderLeaseState string

const (
	FileProviderLeaseStateProvisional FileProviderLeaseState = "provisional"
	FileProviderLeaseStateCommitted   FileProviderLeaseState = "committed"
	FileProviderLeaseStateReleased    FileProviderLeaseState = "released"
)

type BrokerCommandKind string

const (
	BrokerCommandKindRegisterDomain BrokerCommandKind = "register_domain"
	BrokerCommandKindRemoveDomain   BrokerCommandKind = "remove_domain"
	BrokerCommandKindListDomains    BrokerCommandKind = "list_domains"
	BrokerCommandKindSignalDomain   BrokerCommandKind = "signal_domain"
)

type ObjectID string
type MutationRequestID string
type MutationID string
type OperationID string
type MaterializationSnapshotID string

type TenantID string
type DomainID string
type ObservedDomainID string
type OwnerID string
type PresentationInstanceID string
type SourceAuthorityID string
type ChangeID string
type ActivationChangeID string

type CatalogObject struct {
	ID               ObjectID   `json:"id"`
	ParentID         ObjectID   `json:"parent_id"`
	Revision         uint64     `json:"revision"`
	MetadataRevision uint64     `json:"metadata_revision"`
	ContentRevision  uint64     `json:"content_revision"`
	Name             string     `json:"name"`
	Kind             ObjectKind `json:"kind"`
	Mode             uint32     `json:"mode"`
	Size             uint64     `json:"size"`
	Hash             string     `json:"hash"`
	LinkTarget       string     `json:"link_target"`
	Desired          uint64     `json:"desired"`
	Observed         uint64     `json:"observed"`
	Verified         uint64     `json:"verified"`
	Applied          uint64     `json:"applied"`
	Tombstone        bool       `json:"tombstone"`
}

type Change struct {
	Revision uint64        `json:"revision"`
	Sequence uint32        `json:"sequence"`
	Kind     ChangeKind    `json:"kind"`
	Object   CatalogObject `json:"object"`
}

type ChangeCursor struct {
	Revision uint64 `json:"revision"`
	Sequence uint32 `json:"sequence"`
}

type CatalogLaneProof struct {
	Tenant     TenantID `json:"tenant"`
	Generation uint64   `json:"generation"`
	Requested  uint64   `json:"requested"`
	Desired    uint64   `json:"desired"`
	Observed   uint64   `json:"observed"`
	Verified   uint64   `json:"verified"`
	Applied    uint64   `json:"applied"`
}

type CriticalObjectRequirement struct {
	LogicalID string `json:"logical_id"`
	Role      string `json:"role"`
}

type ResolvedCriticalObjectProof struct {
	LogicalID       string   `json:"logical_id"`
	Role            string   `json:"role"`
	ObjectID        ObjectID `json:"object_id"`
	ObjectRevision  uint64   `json:"object_revision"`
	ContentRevision uint64   `json:"content_revision"`
	Size            uint64   `json:"size"`
	Hash            string   `json:"hash"`
}

type CriticalReadinessProof struct {
	PolicyDigest           string                        `json:"policy_digest"`
	ResolutionDigest       string                        `json:"resolution_digest"`
	CatalogHead            uint64                        `json:"catalog_head"`
	SourceRevision         uint64                        `json:"source_revision"`
	TenantGeneration       uint64                        `json:"tenant_generation"`
	DomainID               DomainID                      `json:"domain_id"`
	PresentationInstanceID PresentationInstanceID        `json:"presentation_instance_id"`
	RootID                 ObjectID                      `json:"root_id"`
	ActivationGeneration   string                        `json:"activation_generation"`
	Lease                  FileProviderLeaseReceipt      `json:"lease"`
	Objects                []ResolvedCriticalObjectProof `json:"objects"`
}

type FileProviderLeaseReceipt struct {
	LeaseID                string                 `json:"lease_id"`
	TenantID               TenantID               `json:"tenant_id"`
	DomainID               DomainID               `json:"domain_id"`
	Generation             uint64                 `json:"generation"`
	RootID                 ObjectID               `json:"root_id"`
	PresentationInstanceID PresentationInstanceID `json:"presentation_instance_id"`
	State                  FileProviderLeaseState `json:"state"`
	SessionID              string                 `json:"session_id"`
	ProcessIdentity        string                 `json:"process_identity"`
	PolicyDigest           string                 `json:"policy_digest"`
	ResolutionDigest       string                 `json:"resolution_digest"`
	CatalogHead            uint64                 `json:"catalog_head"`
	SourceAuthority        SourceAuthorityID      `json:"source_authority"`
	SourcePublication      OperationID            `json:"source_publication"`
	SourceRevision         uint64                 `json:"source_revision"`
	ActivationGeneration   string                 `json:"activation_generation"`
	ExpiresUnixNano        uint64                 `json:"expires_unix_nano"`
}

type TenantPreparationProof struct {
	Catalog           CatalogLaneProof        `json:"catalog"`
	Presentation      PresentationProof       `json:"presentation"`
	SourceAuthority   SourceAuthorityID       `json:"source_authority"`
	SourcePublication OperationID             `json:"source_publication"`
	SourceRevision    uint64                  `json:"source_revision"`
	CatalogRevision   uint64                  `json:"catalog_revision"`
	ChangeID          ChangeID                `json:"change_id"`
	OperationID       OperationID             `json:"operation_id"`
	CriticalReadiness *CriticalReadinessProof `json:"critical_readiness,omitempty"`
}

type PresentationProof struct {
	Kind         PresentationKind               `json:"kind"`
	Mount        *MountPresentationProof        `json:"mount,omitempty"`
	FileProvider *FileProviderPresentationProof `json:"file_provider,omitempty"`
}

type MountPresentationProof struct {
	TenantID             TenantID `json:"tenant_id"`
	Generation           uint64   `json:"generation"`
	PublicPath           string   `json:"public_path"`
	ActivationGeneration string   `json:"activation_generation"`
}

type FileProviderPresentationProof struct {
	TenantID               TenantID               `json:"tenant_id"`
	DomainID               DomainID               `json:"domain_id"`
	Generation             uint64                 `json:"generation"`
	PublicPath             string                 `json:"public_path"`
	ActivationGeneration   string                 `json:"activation_generation"`
	PresentationInstanceID PresentationInstanceID `json:"presentation_instance_id"`
	RootID                 ObjectID               `json:"root_id"`
}

type SignalTarget struct {
	Kind     SignalTargetKind `json:"kind"`
	ParentID *ObjectID        `json:"parent_id,omitempty"`
}

type EnumerationScope struct {
	Kind     EnumerationScopeKind `json:"kind"`
	ParentID *ObjectID            `json:"parent_id,omitempty"`
}

type BrokerForwardContext struct {
	DomainID   DomainID `json:"domain_id"`
	TenantID   TenantID `json:"tenant_id"`
	Generation uint64   `json:"generation"`
}

type ActivationSourceCause struct {
	PublicationID      OperationID     `json:"publication_id"`
	ChangeID           ChangeID        `json:"change_id"`
	SourceRevision     uint64          `json:"source_revision"`
	OperationID        OperationID     `json:"operation_id"`
	Cause              ActivationCause `json:"cause"`
	AffectedKeysDigest string          `json:"affected_keys_digest"`
}

type ActivationNotification struct {
	Protocol            uint16                  `json:"protocol"`
	ActivationChangeID  ActivationChangeID      `json:"activation_change_id"`
	TenantID            TenantID                `json:"tenant_id"`
	DomainID            DomainID                `json:"domain_id"`
	Generation          uint64                  `json:"generation"`
	ActivationRevision  uint64                  `json:"activation_revision"`
	CatalogHead         uint64                  `json:"catalog_head"`
	HeadDigest          string                  `json:"head_digest"`
	ProviderFingerprint string                  `json:"provider_fingerprint"`
	Causes              []ActivationSourceCause `json:"causes"`
	TargetCount         uint64                  `json:"target_count"`
	TargetDigest        string                  `json:"target_digest"`
	TargetsCoalesced    bool                    `json:"targets_coalesced"`
	Targets             []SignalTarget          `json:"targets"`
}

type DomainRegistration struct {
	DomainID               DomainID               `json:"domain_id"`
	OwnerID                OwnerID                `json:"owner_id"`
	TenantID               TenantID               `json:"tenant_id"`
	Generation             uint64                 `json:"generation"`
	RootID                 ObjectID               `json:"root_id"`
	AccessMode             TenantAccessMode       `json:"access_mode"`
	PresentationInstanceID PresentationInstanceID `json:"presentation_instance_id"`
	DisplayName            string                 `json:"display_name"`
}

type RegisteredDomain struct {
	DomainID               DomainID               `json:"domain_id"`
	OwnerID                OwnerID                `json:"owner_id"`
	TenantID               TenantID               `json:"tenant_id"`
	Generation             uint64                 `json:"generation"`
	RootID                 ObjectID               `json:"root_id"`
	AccessMode             TenantAccessMode       `json:"access_mode"`
	PresentationInstanceID PresentationInstanceID `json:"presentation_instance_id"`
	DisplayName            string                 `json:"display_name"`
	PublicPath             string                 `json:"public_path"`
}

type ObservedDomain struct {
	ObservedID ObservedDomainID  `json:"observed_id"`
	Managed    *RegisteredDomain `json:"managed,omitempty"`
}

type SourceAuthorityDeclaration struct {
	Authority         SourceAuthorityID `json:"authority"`
	DriverID          string            `json:"driver_id"`
	DriverConfig      []byte            `json:"driver_config"`
	DeclarationDigest string            `json:"declaration_digest"`
}

type DesiredSourceFleetState struct {
	Owner              string `json:"owner"`
	Generation         uint64 `json:"generation"`
	AuthorityCount     uint64 `json:"authority_count"`
	AuthoritiesDigest  string `json:"authorities_digest"`
	DeclarationsDigest string `json:"declarations_digest"`
}

type PublishDesiredSourceFleetRequest struct {
	Protocol           uint16                       `json:"protocol"`
	Owner              string                       `json:"owner"`
	ExpectedGeneration uint64                       `json:"expected_generation"`
	Generation         uint64                       `json:"generation"`
	Declarations       []SourceAuthorityDeclaration `json:"declarations"`
}

type PublishDesiredSourceFleetResponse struct {
	Protocol uint16                   `json:"protocol"`
	Code     ErrorCode                `json:"code"`
	Message  string                   `json:"message"`
	State    *DesiredSourceFleetState `json:"state,omitempty"`
}

type ReadDesiredSourceFleetRequest struct {
	Protocol       uint16             `json:"protocol"`
	Owner          string             `json:"owner"`
	Generation     uint64             `json:"generation"`
	SnapshotDigest *string            `json:"snapshot_digest,omitempty"`
	After          *SourceAuthorityID `json:"after,omitempty"`
	Limit          uint32             `json:"limit"`
}

type ReadDesiredSourceFleetResponse struct {
	Protocol     uint16                       `json:"protocol"`
	Code         ErrorCode                    `json:"code"`
	Message      string                       `json:"message"`
	State        *DesiredSourceFleetState     `json:"state,omitempty"`
	Declarations []SourceAuthorityDeclaration `json:"declarations"`
	Next         *SourceAuthorityID           `json:"next,omitempty"`
}

type BrokerOpenRequest struct {
	Protocol uint16 `json:"protocol"`
}

type BrokerOpenResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}

type BrokerBindDomainRequest struct {
	Protocol   uint16   `json:"protocol"`
	DomainID   DomainID `json:"domain_id"`
	TenantID   TenantID `json:"tenant_id"`
	Generation uint64   `json:"generation"`
}

type BrokerBindDomainResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}

type BrokerForwardRequest struct {
	Protocol  uint16               `json:"protocol"`
	Context   BrokerForwardContext `json:"context"`
	Operation Operation            `json:"operation"`
	Payload   []byte               `json:"payload"`
}

type BrokerCommand struct {
	Protocol        uint16                  `json:"protocol"`
	CommandID       uint64                  `json:"command_id"`
	Kind            BrokerCommandKind       `json:"kind"`
	Registration    *DomainRegistration     `json:"registration,omitempty"`
	ObservedID      *ObservedDomainID       `json:"observed_id,omitempty"`
	Notification    *ActivationNotification `json:"notification,omitempty"`
	AfterObservedID *ObservedDomainID       `json:"after_observed_id,omitempty"`
}

type BrokerResult struct {
	Protocol            uint16            `json:"protocol"`
	Code                ErrorCode         `json:"code"`
	Message             string            `json:"message"`
	CommandID           uint64            `json:"command_id"`
	Kind                BrokerCommandKind `json:"kind"`
	Registered          *RegisteredDomain `json:"registered,omitempty"`
	ConfirmedAbsent     *bool             `json:"confirmed_absent,omitempty"`
	Domains             *[]ObservedDomain `json:"domains,omitempty"`
	SignalAccepted      *bool             `json:"signal_accepted,omitempty"`
	NextAfterObservedID *ObservedDomainID `json:"next_after_observed_id,omitempty"`
}

type RootRequest struct {
	Protocol   uint16 `json:"protocol"`
	Generation uint64 `json:"generation"`
}

type HeadRequest struct {
	Protocol   uint16 `json:"protocol"`
	Generation uint64 `json:"generation"`
}

type HeadResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Revision uint64    `json:"revision"`
}

type SnapshotRequest struct {
	Protocol   uint16           `json:"protocol"`
	Generation uint64           `json:"generation"`
	Revision   uint64           `json:"revision"`
	Scope      EnumerationScope `json:"scope"`
	After      *ObjectID        `json:"after,omitempty"`
	Limit      uint32           `json:"limit"`
}

type SnapshotResponse struct {
	Protocol uint16          `json:"protocol"`
	Code     ErrorCode       `json:"code"`
	Message  string          `json:"message"`
	Revision uint64          `json:"revision"`
	Objects  []CatalogObject `json:"objects"`
	Next     *ObjectID       `json:"next,omitempty"`
}

type ChangesSinceRequest struct {
	Protocol   uint16           `json:"protocol"`
	Generation uint64           `json:"generation"`
	Cursor     ChangeCursor     `json:"cursor"`
	Scope      EnumerationScope `json:"scope"`
	Limit      uint32           `json:"limit"`
}

type ChangesSinceResponse struct {
	Protocol uint16       `json:"protocol"`
	Code     ErrorCode    `json:"code"`
	Message  string       `json:"message"`
	Floor    uint64       `json:"floor"`
	Head     uint64       `json:"head"`
	Next     ChangeCursor `json:"next"`
	Complete bool         `json:"complete"`
	Changes  []Change     `json:"changes"`
}

type LookupRequest struct {
	Protocol   uint16   `json:"protocol"`
	Generation uint64   `json:"generation"`
	ObjectID   ObjectID `json:"object_id"`
}

type LookupNameRequest struct {
	Protocol   uint16   `json:"protocol"`
	Generation uint64   `json:"generation"`
	ParentID   ObjectID `json:"parent_id"`
	Name       string   `json:"name"`
}

type LookupResponse struct {
	Protocol uint16         `json:"protocol"`
	Code     ErrorCode      `json:"code"`
	Message  string         `json:"message"`
	Object   *CatalogObject `json:"object,omitempty"`
}

type OpenAtRequest struct {
	Protocol   uint16   `json:"protocol"`
	Generation uint64   `json:"generation"`
	ObjectID   ObjectID `json:"object_id"`
	Revision   uint64   `json:"revision"`
}

type OpenAtResponse struct {
	Protocol uint16         `json:"protocol"`
	Code     ErrorCode      `json:"code"`
	Message  string         `json:"message"`
	Object   *CatalogObject `json:"object,omitempty"`
}

type MutationRequest struct {
	Protocol         uint16            `json:"protocol"`
	RequestID        MutationRequestID `json:"request_id"`
	Generation       uint64            `json:"generation"`
	ExpectedRevision uint64            `json:"expected_revision"`
	Kind             MutationKind      `json:"kind"`
	ObjectKind       *ObjectKind       `json:"object_kind,omitempty"`
	HasContent       bool              `json:"has_content"`
	ObjectID         *ObjectID         `json:"object_id,omitempty"`
	ParentID         *ObjectID         `json:"parent_id,omitempty"`
	TargetID         *ObjectID         `json:"target_id,omitempty"`
	Name             *string           `json:"name,omitempty"`
	Mode             *uint32           `json:"mode,omitempty"`
	ContentRevision  *uint64           `json:"content_revision,omitempty"`
	LinkTarget       *string           `json:"link_target,omitempty"`
}

type MutationResponse struct {
	Protocol    uint16             `json:"protocol"`
	Code        ErrorCode          `json:"code"`
	Message     string             `json:"message"`
	RequestID   *MutationRequestID `json:"request_id,omitempty"`
	MutationID  *MutationID        `json:"mutation_id,omitempty"`
	Revision    uint64             `json:"revision"`
	PrimaryID   *ObjectID          `json:"primary_id,omitempty"`
	SecondaryID *ObjectID          `json:"secondary_id,omitempty"`
}

type PrepareTenantRequest struct {
	Protocol             uint16                      `json:"protocol"`
	Generation           uint64                      `json:"generation"`
	Presentation         PresentationKind            `json:"presentation"`
	ActivationGeneration string                      `json:"activation_generation"`
	CriticalPolicyDigest string                      `json:"critical_policy_digest"`
	CriticalObjects      []CriticalObjectRequirement `json:"critical_objects"`
	LeaseID              string                      `json:"lease_id"`
	LeaseExpiresUnixNano uint64                      `json:"lease_expires_unix_nano"`
}

type PrepareTenantResponse struct {
	Protocol uint16                  `json:"protocol"`
	Code     ErrorCode               `json:"code"`
	Message  string                  `json:"message"`
	Proof    *TenantPreparationProof `json:"proof,omitempty"`
}

type CommitFileProviderLeaseRequest struct {
	Protocol uint16                   `json:"protocol"`
	Lease    FileProviderLeaseReceipt `json:"lease"`
}

type CommitFileProviderLeaseResponse struct {
	Protocol uint16                    `json:"protocol"`
	Code     ErrorCode                 `json:"code"`
	Message  string                    `json:"message"`
	Lease    *FileProviderLeaseReceipt `json:"lease,omitempty"`
}

type RenewFileProviderLeaseRequest struct {
	Protocol uint16                   `json:"protocol"`
	Lease    FileProviderLeaseReceipt `json:"lease"`
}

type RenewFileProviderLeaseResponse struct {
	Protocol uint16                    `json:"protocol"`
	Code     ErrorCode                 `json:"code"`
	Message  string                    `json:"message"`
	Lease    *FileProviderLeaseReceipt `json:"lease,omitempty"`
}

type ReleaseFileProviderLeaseRequest struct {
	Protocol uint16                   `json:"protocol"`
	Lease    FileProviderLeaseReceipt `json:"lease"`
}

type ReleaseFileProviderLeaseResponse struct {
	Protocol uint16                    `json:"protocol"`
	Code     ErrorCode                 `json:"code"`
	Message  string                    `json:"message"`
	Lease    *FileProviderLeaseReceipt `json:"lease,omitempty"`
}

type AckActivationRequest struct {
	Protocol           uint16             `json:"protocol"`
	ActivationChangeID ActivationChangeID `json:"activation_change_id"`
	DomainID           DomainID           `json:"domain_id"`
	Generation         uint64             `json:"generation"`
	ActivationRevision uint64             `json:"activation_revision"`
	CatalogHead        uint64             `json:"catalog_head"`
	HeadDigest         string             `json:"head_digest"`
}

type AckActivationResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}

type BeginMaterializationSnapshotRequest struct {
	Protocol             uint16                    `json:"protocol"`
	TenantID             TenantID                  `json:"tenant_id"`
	DomainID             DomainID                  `json:"domain_id"`
	Generation           uint64                    `json:"generation"`
	SnapshotID           MaterializationSnapshotID `json:"snapshot_id"`
	BackingStoreIdentity []byte                    `json:"backing_store_identity"`
}

type BeginMaterializationSnapshotResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Epoch    uint64    `json:"epoch"`
}

type SuspendMaterializationSnapshotRequest struct {
	Protocol   uint16   `json:"protocol"`
	TenantID   TenantID `json:"tenant_id"`
	DomainID   DomainID `json:"domain_id"`
	Generation uint64   `json:"generation"`
}

type SuspendMaterializationSnapshotResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}

type StageMaterializationSnapshotPageRequest struct {
	Protocol             uint16                    `json:"protocol"`
	TenantID             TenantID                  `json:"tenant_id"`
	DomainID             DomainID                  `json:"domain_id"`
	Generation           uint64                    `json:"generation"`
	SnapshotID           MaterializationSnapshotID `json:"snapshot_id"`
	BackingStoreIdentity []byte                    `json:"backing_store_identity"`
	Sequence             uint32                    `json:"sequence"`
	ContainerIDs         []ObjectID                `json:"container_ids"`
}

type StageMaterializationSnapshotPageResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
}

type CommitMaterializationSnapshotRequest struct {
	Protocol             uint16                    `json:"protocol"`
	TenantID             TenantID                  `json:"tenant_id"`
	DomainID             DomainID                  `json:"domain_id"`
	Generation           uint64                    `json:"generation"`
	SnapshotID           MaterializationSnapshotID `json:"snapshot_id"`
	BackingStoreIdentity []byte                    `json:"backing_store_identity"`
	PageCount            uint32                    `json:"page_count"`
}

type CommitMaterializationSnapshotResponse struct {
	Protocol uint16    `json:"protocol"`
	Code     ErrorCode `json:"code"`
	Message  string    `json:"message"`
	Revision uint64    `json:"revision"`
	Added    uint64    `json:"added"`
	Removed  uint64    `json:"removed"`
}
